import type { CodegenConfiguration } from "src/types/CodegenConfiguration";
import { getHookNames } from "src/utils/getHookNames";
import { getImportSpecifier } from "src/utils/getImportSpecifier";

/** Aliases only when the names differ, so the common case reads as a plain import. */
const importBinding = (exported: string, local: string) => {
  if (exported === local) {
    return local;
  }

  return `${exported} as ${local}`;
};

export const GENERATED_HEADER =
  "// Generated by react-centrifugo-codegen. Do not edit.\n";

export const renderHooks = (
  configuration: CodegenConfiguration,
  events: string[],
) => {
  const hooks = getHookNames(events, configuration.hookNames);
  const eventModule = JSON.stringify(
    getImportSpecifier(configuration.output, configuration.events.file),
  );
  const dispatcherModule = JSON.stringify(
    getImportSpecifier(configuration.output, configuration.dispatcher.file),
  );
  const files = new Map<string, string>();

  hooks.forEach(({ event, name }) => {
    files.set(
      `${name}.ts`,
      `${GENERATED_HEADER}import type { PublicationHandler, UseChannelOptions } from "react-centrifugo";
import type { ${importBinding(configuration.events.type, "RealtimeEvents")} } from ${eventModule};
import { ${importBinding(configuration.dispatcher.export, "useChannelEvent")} } from ${dispatcherModule};

type EventDefinition = RealtimeEvents[${JSON.stringify(event)}];

export const ${name} = (
  channel: EventDefinition["channel"],
  onEvent: PublicationHandler<EventDefinition["payload"]>,
  options: UseChannelOptions<EventDefinition["payload"]> = {},
) => {
  return useChannelEvent(channel, ${JSON.stringify(event)}, onEvent, options);
};
`,
    );
  });

  const exports = hooks
    .map(({ name }) => `export { ${name} } from "./${name}.js";`)
    .join("\n");
  files.set("index.ts", `${GENERATED_HEADER}${exports}\n`);

  return files;
};
