name: codegen-test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
      - "eslint.config.js"
      - "vitest.config.ts"
      - ".github/actions/setup/**"
      - ".github/workflows/codegen.test.yml"
      - "packages/codegen/**"
  push:
    branches:
      - "main"
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
      - "eslint.config.js"
      - "vitest.config.ts"
      - ".github/actions/setup/**"
      - ".github/workflows/codegen.test.yml"
      - "packages/codegen/**"

permissions:
  contents: read

defaults:
  run:
    working-directory: packages/codegen

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup workspace
        uses: ./.github/actions/setup

      - name: Linting Typescript
        run: pnpm lint:typescript

      - name: Linting Eslint
        run: pnpm lint:eslint

      - name: Unit tests
        run: pnpm test:unit

      - name: Build
        run: pnpm build

      - name: Configuration schema is current
        run: git diff --exit-code -- config.schema.json
